#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# T.10: the monthly article generator. Front-loads a batch of draft posts,
# one per destination, from the next unwritten topic in scripts/t10/topics.yaml.
# Each post is written by `claude -p` to the house rules, has its IMAGE:
# placeholders resolved to licensed Wikimedia photos, is dated into the coming
# weeks, and is left as draft:true tagged "auto". The batch opens ONE pull
# request for human review; nothing publishes until a person clears the draft
# flag.
#
# Usage: scripts/generate_articles.sh [--count N] [--no-pr]
#   --count N   posts to write this run (default: one per destination, 3)
#   --no-pr     write and commit to a branch but do not open a PR
#
# Run by hand once before arming the timer. Safe to re-run: topics already
# written (a post with that slug exists) are skipped.
set -o errexit -o nounset -o pipefail
cd "$(dirname "$0")/.."
repo_root="$(pwd)"

count=3
open_pr=1
while [ $# -gt 0 ]; do
  case "$1" in
    --count) count="$2"; shift 2 ;;
    --no-pr) open_pr=0; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# Refresh main so we branch from the latest content.
git fetch -q origin
git checkout -q main
git pull -q --ff-only origin main

nonce="$(bash scripts/generate_nonce.sh 2>/dev/null || python3 -c 'import random,string;print("".join(random.choices(string.ascii_letters,k=6)))')"
today="$(date -u +%Y%m%d)"
branch="ai-dev-${today}-${nonce}-articles"
git checkout -q -b "$branch"

# Pick the next unwritten topics and generate.
written=0
mapfile -t plan < <(python3 scripts/t10/pick_topics.py "$count")
if [ "${#plan[@]}" -eq 0 ]; then
  echo "no unwritten topics left in the queue; nothing to do"
  git checkout -q main; git branch -q -D "$branch"; exit 0
fi

week=1
for row in "${plan[@]}"; do
  # row is TSV: dest \t slug \t title_hint \t season \t prefer_images \t listing \t banned
  IFS=$'\t' read -r dest slug hint season prefer listing banned <<<"$row"
  pubdate="$(date -u -d "+$((week*7)) days" +%Y-%m-%d)"   # spread across coming weeks
  week=$((week+1))
  out="content/post/${today}-${slug}.md"
  echo "generating: ${dest} / ${slug} (publish ${pubdate})"
  {
    cat scripts/t10/prompt.md
    printf '\n\n---\nGENERATION INPUTS\n'
    printf 'Destination: %s\nTopic: %s\nSlug: %s\nSeason: %s\n' "$dest" "$hint" "$slug" "$season"
    printf 'Image preference: %s\nListing filter URL: %s\n' "$prefer" "$listing"
    printf 'Publication date: %s\nBanned topic (never write about this): %s\n' "$pubdate" "$banned"
  } | claude -p --permission-mode plan > "$out" 2>/dev/null || {
    echo "  claude failed for ${slug}; skipping" >&2; rm -f "$out"; continue
  }
  # Strip any stray code fences the model may wrap the file in.
  sed -i '/^```/d' "$out"
  # Resolve IMAGE: placeholders to licensed local images.
  python3 scripts/t10/fetch_images.py "$out" || {
    echo "  image resolution failed for ${slug}; skipping" >&2; git checkout -q -- . 2>/dev/null || true; rm -f "$out"; continue
  }
  # Safety: enforce draft + auto, and refuse the banned topic.
  grep -q '^draft: true' "$out" || sed -i '0,/^---$/{/^title:/a draft: true
}' "$out"
  grep -qi "$banned" "$out" && { echo "  banned topic leaked into ${slug}; dropping" >&2; rm -f "$out"; continue; }
  written=$((written+1))
done

if [ "$written" -eq 0 ]; then
  echo "no posts were produced"; git checkout -q main; git branch -q -D "$branch"; exit 1
fi

# Verify the site still builds and every reference resolves before proposing.
bazel build //:site >/dev/null 2>&1
scripts/check_local_refs.sh bazel-bin/site

git add content/post static/img/auto
git commit -q -F - <<MSG
feat(blog): ${written} auto-drafted destination article(s)

Generated by scripts/generate_articles.sh (T.10). Each post is draft:true
and tagged auto, written to the house prose rules with licensed Wikimedia
images and linkified key terms, dated into the coming weeks. A human
reviews and clears the draft flag before anything publishes.

This commit has been created by an automated coding assistant,
with human supervision.

Prompt: scripts/generate_articles.sh (T.10 monthly run)
MSG
git push -q -u origin "$branch"

if [ "$open_pr" -eq 1 ]; then
  gh pr create --base main --head "$branch" \
    --title "feat(blog): ${written} auto-drafted destination article(s)" \
    --body "Automated T.10 batch: ${written} draft post(s), one per destination from the topic queue. All draft:true + auto-tagged with licensed images and linkified terms. Review each, then clear \`draft: true\` to publish. Preflight (check_local_refs) passed." || true
fi
echo "done: ${written} draft post(s) on branch ${branch}"
